FROM eclipse-temurin:21-jdk-alpine

# Timezone 설정
ENV TZ="Asia/Seoul"

# 파일 시스템 내에서 /tmp 디렉토리를 Docker 컨테이너의 볼륨으로 사용
VOLUME /tmp

# microdnf 또는 dnf 사용
RUN apk update && \
    apk add --no-cache imagemagick && \
    rm -rf /var/cache/apk/*


# JAR 파일 복사
COPY build/libs/concert-mania-1.1.0.jar ConcertService.jar

# 빌드 아규먼트로 받는 값들 정의
ARG DB_USER_URL
ARG DB_USERNAME
ARG DB_PASSWORD
ARG DB_PRIMARY_URL
ARG REDIS_HOST
ARG RABBITMQ_HOST
ARG RABBITMQ_PORT
ARG RABBITMQ_USERNAME
ARG RABBITMQ_PASSWORD
ARG AES_KEY
ARG SECURITY_TOKEN_HMAC_KEY
ARG EXTENDS_JWT_SECRET_KEY
ARG JWT_ACCESS_TOKEN_VALIDITY
ARG JWT_REFRESH_TOKEN_VALIDITY
ARG JWT_REFRESH_TOKEN_COOKIE_NAME
ARG JWT_ONETIME_TOKEN_VALIDITY
ARG MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
ARG MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
ARG MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED

# 환경 변수 설정
ENV DB_USER_URL=$DB_USER_URL
ENV DB_USERNAME=$DB_USERNAME
ENV DB_PASSWORD=$DB_PASSWORD
ENV DB_PRIMARY_URL=$DB_PRIMARY_URL
ENV REDIS_HOST=$REDIS_HOST
ENV RABBITMQ_HOST=$RABBITMQ_HOST
ENV RABBITMQ_PORT=$RABBITMQ_PORT
ENV RABBITMQ_USERNAME=$RABBITMQ_USERNAME
ENV RABBITMQ_PASSWORD=$RABBITMQ_PASSWORD
ENV AES_KEY=$AES_KEY
ENV SECURITY_TOKEN_HMAC_KEY=$SECURITY_TOKEN_HMAC_KEY
ENV EXTENDS_JWT_SECRET_KEY=$EXTENDS_JWT_SECRET_KEY
ENV JWT_ACCESS_TOKEN_VALIDITY=$JWT_ACCESS_TOKEN_VALIDITY
ENV JWT_REFRESH_TOKEN_VALIDITY=$JWT_REFRESH_TOKEN_VALIDITY
ENV JWT_REFRESH_TOKEN_COOKIE_NAME=$JWT_REFRESH_TOKEN_COOKIE_NAME
ENV JWT_ONETIME_TOKEN_VALIDITY=$JWT_ONETIME_TOKEN_VALIDITY
ENV MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=$MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
ENV MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS=$MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
ENV MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED=$MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED


# JVM 메모리 비율 설정 (초기 힙 50%, 최대 힙 70%)
ENV JAVA_OPTS="-XX:InitialRAMPercentage=50.0 -XX:MaxRAMPercentage=70.0"

# 애플리케이션 실행 명령어에 OpenTelemetry 에이전트 추가
ENTRYPOINT ["sh", "-c", "java -jar ConcertService.jar"]
