spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_USER_URL:jdbc:mysql://localhost:3306/concert?rewriteBatchedStatements=true&useSSL=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate # 운영 환경에서는 validate 사용
    show-sql: false # 운영 환경에서는 SQL 로그 비활성화
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 5000
          max-attempts: 3
          max-interval: 10000
          multiplier: 2

# 운영 환경 로깅 설정
logging:
  level:
    concert.mania.concert: INFO
    root: WARN
    org.springframework.web: INFO
    org.hibernate: INFO
  file:
    name: logs/application.log
    max-size: 10MB
    max-history: 30
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# 운영 환경 보안 설정
aes:
  key: ${AES_KEY:concert-mania-aeskey-prod}
security:
  token:
    hmac-key: ${HMAC_KEY:concert-mania-hash-key-prod}
extends:
  jwt:
    secret-key: ${JWT_SECRET_KEY:concert-mania-secret-key-prod}