{
 "title": "RabbitMQ Metrics",
 "tags": [
  "rabbitmq",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RabbitMQ Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_connections" }
   ]
  },
  {
   "title": "RabbitMQ Channels",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_channels" }
   ]
  },
  {
   "title": "RabbitMQ Messages Ready",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_queue_messages_ready" }
   ]
  },
  {
   "title": "RabbitMQ Messages Published/Delivered",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_published_total",
     "legendFormat": "Published"
    },
    {
     "expr": "rabbitmq_queue_messages_delivered_total",
     "legendFormat": "Delivered"
    }
   ]
  }
 ]
}