{
 "title": "Redis Metrics",
 "tags": [
  "redis",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Redis Connected Clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "redis_connected_clients" }
   ]
  },
  {
   "title": "Redis Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "redis_memory_used_bytes" }
   ]
  },
  {
   "title": "Redis Command Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total[5m])"
    }
   ]
  },
  {
   "title": "Redis Cache Hits/Misses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "redis_keyspace_hits_total", "legendFormat": "Hits" },
    { "expr": "redis_keyspace_misses_total", "legendFormat": "Misses" }
   ]
  }
 ]
}